# Generated by Django 2.0.3 on 2018-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('stdID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('sflag', models.BooleanField(default=True)),
                ('mflag', models.BooleanField(default=False)),
            ],
        ),
    ]
