# Generated by Django 2.0.3 on 2018-04-02 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=30, null=True)),
                ('content', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewUpload',
            fields=[
                ('slNo', models.AutoField(primary_key=True, serialize=False)),
                ('Course_Title', models.CharField(default='CSE370', max_length=10, null=True)),
                ('Lecture_Date', models.DateField(default='2018-4-10', null=True)),
                ('Size', models.TextField(max_length=4, null=True)),
                ('Department_Name', models.CharField(default='CSE', max_length=30, null=True)),
                ('Choose_File', models.FileField(upload_to='files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Selected_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person')),
            ],
        ),
        migrations.CreateModel(
            name='NewUpload2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=30, null=True)),
                ('courseTitle', models.CharField(max_length=30, null=True)),
                ('faculty', models.CharField(max_length=30, null=True)),
                ('newUpload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileUpload.NewUpload')),
            ],
        ),
        migrations.AddField(
            model_name='contentinfo',
            name='newUpload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileUpload.NewUpload'),
        ),
    ]
