# Generated by Django 2.0.3 on 2018-04-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newupload',
            old_name='slNo',
            new_name='Serial_NO',
        ),
        migrations.RemoveField(
            model_name='newupload',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='newupload',
            name='Size',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
