# Generated by Django 2.0.3 on 2018-04-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email', max_length=254)),
                ('password', models.CharField(default='password', max_length=30)),
            ],
        ),
    ]
